name: go
# 打包go项目
on:
  push:
    branches:
      - master

# win,mac,linux
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Build
        run: go build -o main
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: main