name: Go Build with config.txt

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Copy config.txt
      run: cp config.txt ${{ github.workspace }}

    - name: Build Go Binary
      run: go build -o my_binary .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0  # 替换为你的版本号
        release_name: Release v1.0.0  # 替换为你的版本号和名称
        body: |
          Changes in this release.

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./my_binary
        asset_name: my_binary
        asset_content_type: application/octet-stream

    - name: Upload config.txt
      id: upload-config
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./config.txt
        asset_name: config.txt
        asset_content_type: application/octet-stream
